### ISSUE TITLE
Problem parsing table names when using backticks

### ISSUE THREAD

**Issue by avramovic** [marcocesarato/PHP-Light-SQL-Parser-Class#1]
Hi, I have a problem parsing queries where table names are wrapped with backticks (`)

    $parser = new \marcocesarato\sqlparser\LightSQLParser( 'SELECT * FROM `tablename`' );
    var_dump($parser->table()); // -> (empty string)

For now I'm working around it by removing backticks:

    $parser = new \marcocesarato\sqlparser\LightSQLParser( str_replace('`', '', 'SELECT * FROM `tablename`') );
    var_dump($parser->table()); // -> "tablename"

**Comment by marcocesarato** [comment]
Solved on last release
